#!/usr/bin/python

import subprocess
import sys
import time
#import statistics

#print "Start\n"
#runList = []
#for i in range(7):
start = time.time()
subprocess.call([sys.argv[1], sys.argv[2], sys.argv[3]])
end = time.time()
#runList.append(end-start)
print "Program runtime is " + (str)(end-start) + "s\n"
#print "End\n" #+ (str)(end - start)
#total = 0
#for i in range(5, 0, -1):
#    total += runList[-i]
#avg = total/5
#print "Average runtime is " + (str)(avg) + "s"
#totaldev = 0
#for i in range(5, 0, -1):
#    totaldev += abs(runList[-i] -avg)
#print "Standard deviation is " + (str)(totaldev/5) + "s"
